-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
--

-- local is_git_dir = function()
--   return os.execute("git rev-parse --is-inside-work-tree >> /dev/null 2>&1")
-- end
--
-- vim.api.nvim_create_autocmd("VimEnter", {
--   callback = function()
--     local bufferPath = vim.fn.expand("%:p")
--     if vim.fn.isdirectory(bufferPath) ~= 0 then
--       local ts_builtin = require("telescope.builtin")
--       vim.api.nvim_buf_delete(0, { force = true })
--       if is_git_dir() == 0 then
--         ts_builtin.git_files({ show_untracked = true })
--       else
--         ts_builtin.find_files()
--       end
--     end
--   end,
-- })

-- vim.api.nvim_create_autocmd("VimEnter", {
--   callback = function()
--     if vim.fn.argc() == 0 then
--       LazyVim.pick("auto")
--     end
--   end,
-- })

-- vim.api.nvim_create_autocmd("VimEnter", {
--   desc = "Auto select virtualenv Nvim open",
--   pattern = "*",
--   callback = function()
--     local venv = vim.fn.findfile("pyproject.toml", vim.fn.getcwd() .. ";")
--     if venv ~= "" then
--       require("venv-selector").retrieve_from_cache()
--     end
--   end,
--   once = true,
-- })

-- Add any additional autocmds here
